### ISSUE TITLE
2023 SANS SOC Survey Review - Error rendering embedded code - Invalid PDF

### ISSUE THREAD

**Issue by JeremyNGalloway** [SpecterOps/presentations#3]
SO-CON 2024/Christopher Crowley - 2023 SANS SOC Survey Review/Christopher Crowley - 2023 SANS SOC Survey Review - SO-CON 2024.pdf

Invalid PDF

**Comment by chrismaddalena** [comment]
Thanks for letting us know! We're tracking this. Christopher is going to send us a new copy.
